# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect_tiezi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.CharField(max_length=50)),
                ('tiezi_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Good_num_maincomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_good_man', models.CharField(max_length=50)),
                ('get_good_man', models.CharField(max_length=50)),
                ('main_comment_id', models.IntegerField()),
                ('isread', models.BooleanField(default=0)),
                ('isdelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Good_num_tiezi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_good_man', models.CharField(max_length=50)),
                ('get_good_man', models.CharField(max_length=50)),
                ('tiezi_id', models.IntegerField()),
                ('isread', models.BooleanField(default=0)),
                ('isdelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Main_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiezi_id', models.IntegerField()),
                ('main_openor', models.CharField(max_length=50)),
                ('com_content', models.CharField(max_length=200)),
                ('good_num', models.IntegerField(default=0)),
                ('to_man', models.CharField(max_length=50)),
                ('main_isread', models.BooleanField(default=0)),
                ('opentime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('only_title', models.CharField(db_index=True, default=0, max_length=100)),
                ('content', models.TextField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('img1', models.CharField(default='nopicture', max_length=200)),
                ('img2', models.CharField(default='nopicture', max_length=200)),
                ('img3', models.CharField(default='nopicture', max_length=200)),
                ('top', models.BooleanField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('good_num', models.IntegerField(default=0)),
                ('isswiper', models.BooleanField(default=0)),
                ('isdelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Side_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_comment_id', models.IntegerField()),
                ('side_openor', models.CharField(max_length=50)),
                ('side_com_content', models.CharField(max_length=200)),
                ('tiezi_id', models.IntegerField(default=0)),
                ('to_man', models.CharField(max_length=50)),
                ('side_isread', models.BooleanField(default=0)),
                ('opentime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
