# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-03 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsswiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('only_title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=1024)),
                ('time', models.DateField(auto_now_add=True)),
                ('img1', models.CharField(default='nopicture', max_length=200)),
                ('img2', models.CharField(default='nopicture', max_length=200)),
                ('img3', models.CharField(default='nopicture', max_length=200)),
                ('top', models.BooleanField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('good_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='isswiper',
        ),
    ]
