# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190603_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsswiper',
        ),
        migrations.AddField(
            model_name='news',
            name='isswiper',
            field=models.BooleanField(default=0),
        ),
    ]
