# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-03 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190610_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
