# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190705_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='only_title',
            field=models.CharField(db_index=True, default=0, max_length=100),
        ),
    ]
