# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('concern_userid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('fans_userid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(default='nothing', max_length=50)),
                ('openId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nickName', models.CharField(max_length=30)),
                ('gender', models.IntegerField(default=1)),
                ('language', models.CharField(default='none', max_length=10)),
                ('city', models.CharField(default='none', max_length=10)),
                ('province', models.CharField(default='none', max_length=10)),
                ('country', models.CharField(default='none', max_length=10)),
                ('avatarUrl', models.CharField(default='none', max_length=256)),
                ('unionId', models.CharField(max_length=30)),
                ('token', models.CharField(default='nothing', max_length=100, unique=True)),
                ('experience', models.IntegerField(default=0)),
                ('post_num', models.IntegerField(default=0)),
                ('concern_num', models.IntegerField(default=0)),
                ('fans_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='fans',
            name='fans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paly.User'),
        ),
        migrations.AddField(
            model_name='concern',
            name='concern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paly.User'),
        ),
    ]
