# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
