# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('picture_small', models.CharField(max_length=512)),
                ('picture_big', models.CharField(max_length=512)),
                ('look_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('little_img', models.CharField(default=1, max_length=100)),
                ('singger', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('picture_num', models.IntegerField(default=0)),
                ('visit_num', models.IntegerField(default=0)),
                ('isswiper', models.BooleanField(default=0)),
            ],
        ),
    ]
