# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-30 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_concert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocal',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='vocal',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='vocal',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='vocal',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='vocal',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='vocal',
            name='project_connect',
        ),
        migrations.RemoveField(
            model_name='vocal_swiper',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='vocal_swiper',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='vocal_swiper',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='vocal_swiper',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='vocal_swiper',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='vocal_swiper',
            name='project_connect',
        ),
    ]
