# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_concert', '0002_auto_20190530_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('picture_small', models.CharField(max_length=512)),
                ('picture_big', models.CharField(max_length=512)),
                ('look_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='vocal',
            name='picture_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocal',
            name='visit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocal_swiper',
            name='picture_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocal_swiper',
            name='visit_num',
            field=models.IntegerField(default=0),
        ),
    ]
