# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal_concert', '0003_auto_20190530_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vocal_swiper',
        ),
        migrations.AddField(
            model_name='vocal',
            name='isswiper',
            field=models.BooleanField(default=0),
        ),
    ]
