# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('explain', models.CharField(max_length=512)),
                ('time', models.DateField(auto_now_add=True)),
                ('joinnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Activety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paly.User')),
            ],
        ),
    ]
