# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='活动海报')),
                ('name', models.CharField(max_length=255, verbose_name='活动名')),
                ('support', models.CharField(max_length=255, verbose_name='支持商')),
                ('explain', models.CharField(max_length=1024, verbose_name='活动说明')),
                ('endtime', models.DateField(auto_now_add=True, verbose_name='活动截止时间')),
                ('joinnum', models.IntegerField(default=0, verbose_name='参与人数')),
                ('isvote', models.BooleanField(default=0, verbose_name='是否有投票')),
                ('getprize_userid', models.CharField(default=None, max_length=255, verbose_name='获奖人id')),
                ('getprize_nickname', models.CharField(default=None, max_length=255, verbose_name='获奖人昵称')),
            ],
            options={
                'verbose_name_plural': '活动配置',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='优惠券使用说明')),
                ('num', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='优惠金额')),
                ('img', models.CharField(default='', max_length=255, verbose_name='优惠券图片')),
                ('time', models.DateField(auto_now_add=True, verbose_name='过期时间')),
                ('type', models.IntegerField(default=0, verbose_name='周边产品为1，现场服务为2')),
            ],
            options={
                'verbose_name_plural': '优惠券配置',
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=255, unique=True)),
                ('username', models.CharField(default='', max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('activety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Activety', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usercoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(max_length=255, verbose_name='选项名')),
                ('num', models.IntegerField(default=0)),
                ('activety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Activety', verbose_name='活动id')),
            ],
            options={
                'verbose_name_plural': '投票活动投票选项',
            },
        ),
    ]
