# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexswiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=300)),
            ],
        ),
    ]
