# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activety',
            old_name='time',
            new_name='endtime',
        ),
    ]
