# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='activety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Activety'),
        ),
        migrations.AlterField(
            model_name='join',
            name='userid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
