# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0002_auto_20190606_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activety',
            name='joinnum',
            field=models.IntegerField(default=0),
        ),
    ]
