# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0002_auto_20190711_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activety',
            name='endtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='活动截止时间'),
        ),
    ]
