# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0002_indexswiper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activetyid', models.IntegerField(default=2)),
                ('userid', models.CharField(max_length=255)),
                ('choose', models.CharField(max_length=255)),
            ],
        ),
    ]
