# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0003_auto_20190606_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.AddField(
            model_name='join',
            name='userid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='join',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
