# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0003_auto_20190712_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='activety',
            name='appid',
            field=models.CharField(default=None, max_length=255, verbose_name='appid'),
        ),
        migrations.AddField(
            model_name='activety',
            name='apppage',
            field=models.CharField(default=None, max_length=255, verbose_name='apppage'),
        ),
        migrations.AddField(
            model_name='activety',
            name='logurl',
            field=models.CharField(default=None, max_length=255, verbose_name='广告图片url'),
        ),
        migrations.AddField(
            model_name='activety',
            name='weburl',
            field=models.CharField(default=None, max_length=255, verbose_name='跳转网页url'),
        ),
    ]
