# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0004_auto_20190606_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='activety',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
