# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0005_auto_20190606_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('activety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Activety')),
            ],
        ),
    ]
