# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0006_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('num', models.IntegerField(default=0)),
                ('time', models.DateField(auto_now_add=True)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='activety',
            name='getprize_nickname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='activety',
            name='getprize_userid',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
