# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0007_auto_20190610_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Coupon')),
            ],
        ),
    ]
