# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0008_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
