# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-12 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0009_coupon_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(max_length=255)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='activety',
            name='isvote',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='activety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activety.Activety'),
        ),
    ]
