# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0010_auto_20190612_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activety',
            name='explain',
            field=models.CharField(max_length=1024),
        ),
    ]
