# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activety', '0011_auto_20190617_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='num',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
