# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhoubianorders',
            name='sign',
            field=models.CharField(default='qwert', max_length=100),
        ),
    ]
