# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_zhoubianorders_getman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_true_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
