# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-18 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20190618_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhoubian',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
