# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20190618_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhoubianorders',
            name='sign',
        ),
        migrations.AddField(
            model_name='zhoubianorders',
            name='getnum',
            field=models.IntegerField(default=1),
        ),
    ]
