# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-19 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_zhoubianorders_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=50)),
                ('refund_num', models.CharField(max_length=50)),
                ('refund_time', models.DateField(auto_now_add=True)),
                ('refund_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='zhoubianorders',
            old_name='getnum',
            new_name='goodnum',
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='timestamp',
            field=models.CharField(default='111111', max_length=50),
        ),
    ]
