# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20190619_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
