# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-20 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20190619_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhouianorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=50, unique=True)),
                ('order_start_time', models.CharField(max_length=50)),
                ('order_user', models.CharField(max_length=256)),
                ('order_location', models.CharField(max_length=512)),
                ('order_phone', models.CharField(max_length=50)),
                ('couponid', models.IntegerField(default=0)),
                ('zhoubianid', models.IntegerField(default=0)),
                ('goodname', models.CharField(max_length=100)),
                ('goodimg', models.CharField(max_length=150)),
                ('goodprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_true_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('goodnum', models.IntegerField(default=1)),
                ('getman', models.CharField(default='qwert', max_length=50)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='zhoubianorders',
            name='order_good',
        ),
        migrations.DeleteModel(
            name='ZhouBianorders',
        ),
    ]
