# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-20 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20190620_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zhouianorders',
            new_name='ZhouBianorders',
        ),
    ]
