# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_zhoubianorders_receivetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhoubianorders',
            name='waybill_id',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
