# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-25 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20190621_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xianchangorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=50, unique=True)),
                ('order_start_time', models.CharField(max_length=50)),
                ('order_userid', models.CharField(max_length=256)),
                ('order_getman', models.CharField(max_length=50)),
                ('location_site', models.CharField(max_length=512)),
                ('location_seat', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=50)),
                ('couponid', models.IntegerField(default=0)),
                ('order_true_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('orderimg', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Xianchangorder_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.IntegerField(default=0)),
                ('goodnum', models.IntegerField(default=0)),
                ('goodname', models.CharField(max_length=100)),
                ('goodprice', models.DecimalField(decimal_places=1, max_digits=7)),
                ('xianchangorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Xianchangorder')),
            ],
        ),
    ]
