# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_xianchangorder_xianchangorder_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xianchangorder_detail',
            name='xianchangorder',
        ),
        migrations.AddField(
            model_name='xianchangorder',
            name='isget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xianchangorder_detail',
            name='ordernum',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='xianchangorder',
            name='orderimg',
            field=models.CharField(default='http://liulian.szbeacon.com/%E8%BD%AE%E6%92%AD%E7%94%BB%E9%9D%A2_0002_%E7%BB%84-2-%E6%8B%B7%E8%B4%9D.png', max_length=150),
        ),
    ]
