# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20190625_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='xianchangorder_detail',
            name='goodprice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
