# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_auto_20190625_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zhoubianorders',
            options={'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='getman',
            field=models.CharField(default='qwert', max_length=50, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='goodname',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='goodnum',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='goodprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_location',
            field=models.CharField(max_length=512, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_num',
            field=models.CharField(max_length=50, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_phone',
            field=models.CharField(max_length=50, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_start_time',
            field=models.CharField(max_length=50, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_true_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='实付金额'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='order_user',
            field=models.CharField(max_length=256, verbose_name='收货用户ID'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='receivetime',
            field=models.CharField(default='', max_length=50, verbose_name='收货时间'),
        ),
        migrations.AlterField(
            model_name='zhoubianorders',
            name='type',
            field=models.IntegerField(default=1, verbose_name='物流状态'),
        ),
    ]
