# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_auto_20190701_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name_plural': '退款单记录表'},
        ),
        migrations.AlterField(
            model_name='refund',
            name='order_num',
            field=models.CharField(max_length=50, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_num',
            field=models.CharField(max_length=50, verbose_name='退款金额'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_status',
            field=models.BooleanField(default=0, verbose_name='退款是否成功'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='退款时间'),
        ),
    ]
