# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_auto_20190702_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='xianchangorder_detail',
            name='orderForeignKey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.Xianchangorder'),
        ),
    ]
